// <auto-generated />
using Data.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ContextBase))]
    partial class ContextBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Robot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HeadInclination")
                        .HasColumnType("int");

                    b.Property<int>("HeadRotation")
                        .HasColumnType("int");

                    b.Property<int>("LeftElbow")
                        .HasColumnType("int");

                    b.Property<int>("LeftFist")
                        .HasColumnType("int");

                    b.Property<int>("RightElbow")
                        .HasColumnType("int");

                    b.Property<int>("RightFist")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ROBO");
                });
#pragma warning restore 612, 618
        }
    }
}
